<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UploadFile\Module'                        => __DIR__ . '/Module.php',
    'UploadFile\Controller\UploadFileController' => __DIR__ . '/src/UploadFile/Controller/UploadFileController.php',
    'UploadFileTest\Framework\TestCase'        => __DIR__ . '/tests/UploadFile/Framework/TestCase.php',
    'UploadFileTest\SampleTest'                => __DIR__ . '/tests/UploadFile/SampleTest.php',
);
