<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ResourceFolder\Module'                        => __DIR__ . '/Module.php',
    'ResourceFolder\Controller\ResourceFolderController' => __DIR__ . '/src/ResourceFolder/Controller/ResourceFolderController.php',
    'ResourceFolderTest\Framework\TestCase'        => __DIR__ . '/tests/ResourceFolder/Framework/TestCase.php',
    'ResourceFolderTest\SampleTest'                => __DIR__ . '/tests/ResourceFolder/SampleTest.php',
);
